### ISSUE TITLE
Using DataFrames and ScikitLearn fit! warning

### ISSUE THREAD

**Issue by degravek** [cstjean/ScikitLearn.jl#8]
I'm running into another problem using the "fit!" command. I'm using both the DataFrames and SckikitLearn packages, I get this error when trying to use "fit!":

WARNING: both ScikitLearn and DataFrames export "fit!"; uses of it in module Main must be qualified

If I then try to use "fit!", I get the error : ERROR: UndefVarError: fit! not defined. However, "fit!" works fine if I have not declared the usage of both packages. Shouldn't using the function work regardless?

**Comment by cstjean** [comment]
`DataFrames.fit!` and `ScikitLearn.fit!` have different semantics, so they are not the same function, which is why Julia asks you to choose which `fit!` you want. You can solve it by using from DataFrames selectively, for instance:

```julia
using ScikitLearn
using DataFrames: DataFrame, join, merge
```

That way there won't be a warning.

**Comment by degravek** [comment]
Okay, I'm running into even worse problems now. I'm getting:

WARNING: both DataArrays and ScikitLearn export "fit!"; uses of it in module Main must be qualified
ERROR: UndefVarError: fit! not defined

It also appears that MLBase and DataFrame use "fit!". How many packages use this thing? Shouldn't they then have different names? I can't go through every code I write and declare exactly which commands I need from each package. This is especially tough as a newcomer to the Julia language.

**Comment by cstjean** [comment]
That's a good point, but I'm not sure that it's solvable. `fit!` is a very traditional word to use in statistics, which is why `StatsBase` used it. Meanwhile, ScikitLearn.jl is the scikit-learn interface in Julia, and scikit-learn uses `model.fit`, so I can't really deviate from that either.

> I can't go through every code I write and declare exactly which commands I need from each package

In the Python world, that's what everybody does, and it's really not so bad. The Julia habit of `using` packages wholesale is strongly discouraged.

In any case, the other option is that every time you use `fit!`, you write it as `ScikitLearn.fit!`. It's not ideal, but you won't get a warning this way.

**Comment by cstjean** [comment]
I [filed an issue about it](https://github.com/JuliaStats/DataFrames.jl/issues/1003).

**Comment by cstjean** [comment]
I just realized that there's an easier way to resolve the ambiguity:

```julia
using ScikitLearn, DataFrames   # ambiguous fit! calls
using ScikitLearn: fit!       # no more ambiguity

fit!(...)
```

That seems as good as we're likely to get.
